name: KillReward
version: 1.0.0
main: cc.vastsea.killreward.KillRewardPlugin
author: Snowball_233
description: A plugin that rewards players for killing different types of entities
api-version: 1.20
depend: [Vault]
softdepend: [BetterEconomy]

commands:
  killreward:
    description: Main command for KillReward plugin
    usage: /killreward <reload>
    permission: killreward.admin
    aliases: [kr]

permissions:
  killreward.admin:
    description: Allows access to admin commands
    default: op
  killreward.receive:
    description: Allows receiving kill rewards
    default: true
  kr.reload:
    description: Allows reloading the plugin configuration
    default: op